### PR TITLE
Update permanent-delete.js

### LINKED ISSUE #10: Uncaught TypeError: treeView.mainModule.createView is not a function
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.17.0 x64
**Electron**: 1.3.15
**OS**: Unknown Windows version
**Thrown From**: [permanent-delete](https://github.com/olmokramer/atom-permanent-delete) package 0.1.5

### Stack Trace

Uncaught TypeError: treeView.mainModule.createView is not a function

```
At C:\Users\Pr\.atom\packages\permanent-delete\lib\permanent-delete.js:26

TypeError: treeView.mainModule.createView is not a function
    at /packages/permanent-delete/lib/permanent-delete.js:26:34)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.17.0/resources/app/src/command-registry.js:265:1)
    at ~/AppData/Local/atom/app-1.17.0/resources/app/src/command-registry.js:3:1
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (~/AppData/Local/atom/app-1.17.0/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:610:1)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (~/AppData/Local/atom/app-1.17.0/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:401:1)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (~/AppData/Local/atom/app-1.17.0/resources/app/src/window-event-handler.js:100:1)
    at HTMLDocument.<anonymous> (~/AppData/Local/atom/app-1.17.0/resources/app/src/window-event-handler.js:3:1)
```

### Commands

```
     -0:23.1.0 permanent-delete:delete (div.tool-panel.tree-view)
```

### Non-Core Packages

```
permanent-delete 0.1.5 
```

### PR DESCRIPTION
**Pull request by DanChianucci**
tree view package removed createView in atom 1.17
Fixes #10

### CODE REVIEW

**Comment by ethernal** [comment]
I tested the change on 1.17 - it works. @olmokramer can you merge?

**Comment by ais** [comment]
Also tested on 1.17, though I am noticing a decrease in responsiveness in Windows 7. Anyone else?

**Comment by nox-404** [comment]
Please merge !

**Comment by nox-404** [comment]
Tested in 1.17.2 on Windows 10, please **merge ASAP** !!!

(@overkillx I didn't not see any difference in performances)

**Comment by BennyLi** [comment]
@olmokramer Works on Arch Linux with Atom 1.17.2
Would be great if you could merge this simple change so many users can use your plugin again!

**Comment by olmokramer** [comment]
I'm sorry it took so long, I haven't been using Atom for about 2 years now and haven't looked up on my Atom plugins on github as I had a lot of other stuff going. If anyone would like to take over maintenance of this plugin, please do send me an email and I'd be happy to transfer the repository to your account. Cheers

**Comment by Dayjo** [comment]
@olmokramer Thanks for the update, much appreciated :)

**Comment by zorn-v** [comment]
You can transfer it to me

**Comment by olmokramer** [comment]
@zorn-v I've sent you a request for transfer. Good luck with the maintenance!

**Comment by zorn-v** [comment]
~~@olmokramer how to update package on atom.io ?~~
Figured out

**Pull request merged**
