### PR TITLE
Update permanent-delete.js

### PR DESCRIPTION
**Pull request by lierdakil**
Due to update to Electron 6, atom.confirm's API has changed. I've updated the thing to use the new API. Also reformatted because I'm lazy. Sorry about that.

### CODE REVIEW

**Comment by mzedeler** [comment]
I could really use this module now - is there something I can do to help getting this merged?

**Comment by mzedeler** [comment]
@zorn-v ?

**Comment by zorn-v** [comment]
Sorry, missed this PR. 
But it disgusting to make commits where actual changes is hidden behind "reformat"

**Comment by zorn-v** [comment]
And I do not see any incompatibles with `atom.confirm` in current version
https://flight-manual.atom.io/api/v1.53.0/AtomEnvironment/#instance-confirm

**Comment by lierdakil** [comment]
Someone didn't update the docs. The package is broken on newer Atom releases -- otherwise I wouldn't bother. Also, "disgusting"? Really? Well, suit yourself, I'm not interested in prostrating before you. Politely requesting an amendment would've been fine, I would do it -- the reason I did it the way I did is I had zero indication if this project was abandoned or not, so spending extra effort to fight with my auto-formatter was not justified. But now I'm frankly not interested.

If you don't have the intention of maintaining the package and/or if you're not using Atom anymore, I would suggest removing the package altogether, but it's your call obviously.

**Comment by zorn-v** [comment]
> if this project was abandoned or not

I just not have "watch" mark on this repo, so sorry about that. I already add fix it in v0.1.8

**Pull request closed without merging**
